//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('currencies')
export class currenciesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  currencyCode: string;

  @Column('text', { nullable: true })
  name: string;

  @Column('real', { nullable: true })
  exchangeRate: number;
}
