//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('transactions')
export class transactionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('real', { nullable: true })
  amount: number;

  @Column('integer', { nullable: true })
  currency: number;

  @Column('integer', { nullable: true })
  senderId: number;

  @Column('integer', { nullable: true })
  receiverId: number;

  @Column('date', { nullable: true })
  transactionDate: Date;
}
