//Source code generated by AppGPT (www.appgpt.tech)
import "reflect-metadata";
import { app, initialize } from "./app";

const port = process.env.PORT || 3000;

(async function () {
  try {
    await initialize();
    app.listen(port, () =>
      console.log(`App backend listening at http://localhost:${port}`)
    );
  } catch (error) {
    console.error('An error occurred during initialization:', error);
    process.exit(1); // Exit the process with a non-zero exit code to indicate failure
  }
})();

